import { Injectable } from '@angular/core';

export interface User {
  id: number;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  role: 'admin' | 'editor' | 'viewer';
  plan: 'free' | 'pro' | 'enterprise';
  status: 'active' | 'inactive' | 'suspended';
  joinedAt: string;
  lastLoginAt: string;
  storageUsed: number;
  apiCalls: number;
}

const USERS: User[] = [
  {
    id: 1,
    username: 'alice_j',
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@example.com',
    role: 'admin',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-01-15',
    lastLoginAt: '2026-02-25',
    storageUsed: 4800,
    apiCalls: 12450,
  },
  {
    id: 2,
    username: 'bob_s',
    firstName: 'Bob',
    lastName: 'Smith',
    email: 'bob.smith@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'active',
    joinedAt: '2022-03-20',
    lastLoginAt: '2026-02-24',
    storageUsed: 2100,
    apiCalls: 8320,
  },
  {
    id: 3,
    username: 'carol_w',
    firstName: 'Carol',
    lastName: 'Williams',
    email: 'carol.williams@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'active',
    joinedAt: '2022-06-10',
    lastLoginAt: '2026-02-20',
    storageUsed: 340,
    apiCalls: 1200,
  },
  {
    id: 4,
    username: 'david_b',
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.brown@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'active',
    joinedAt: '2022-08-05',
    lastLoginAt: '2026-02-26',
    storageUsed: 3200,
    apiCalls: 9540,
  },
  {
    id: 5,
    username: 'eve_d',
    firstName: 'Eve',
    lastName: 'Davis',
    email: 'eve.davis@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'suspended',
    joinedAt: '2022-09-12',
    lastLoginAt: '2025-11-03',
    storageUsed: 120,
    apiCalls: 450,
  },
  {
    id: 6,
    username: 'frank_m',
    firstName: 'Frank',
    lastName: 'Miller',
    email: 'frank.miller@example.com',
    role: 'admin',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-02-28',
    lastLoginAt: '2026-02-26',
    storageUsed: 7600,
    apiCalls: 24100,
  },
  {
    id: 7,
    username: 'grace_w',
    firstName: 'Grace',
    lastName: 'Wilson',
    email: 'grace.wilson@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'active',
    joinedAt: '2022-11-01',
    lastLoginAt: '2026-02-23',
    storageUsed: 1800,
    apiCalls: 6700,
  },
  {
    id: 8,
    username: 'henry_m',
    firstName: 'Henry',
    lastName: 'Moore',
    email: 'henry.moore@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'inactive',
    joinedAt: '2023-01-18',
    lastLoginAt: '2025-08-14',
    storageUsed: 80,
    apiCalls: 210,
  },
  {
    id: 9,
    username: 'ivy_t',
    firstName: 'Ivy',
    lastName: 'Taylor',
    email: 'ivy.taylor@example.com',
    role: 'editor',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-05-22',
    lastLoginAt: '2026-02-25',
    storageUsed: 5100,
    apiCalls: 15800,
  },
  {
    id: 10,
    username: 'jack_a',
    firstName: 'Jack',
    lastName: 'Anderson',
    email: 'jack.anderson@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'inactive',
    joinedAt: '2023-03-14',
    lastLoginAt: '2025-06-20',
    storageUsed: 50,
    apiCalls: 130,
  },
  {
    id: 11,
    username: 'karen_t',
    firstName: 'Karen',
    lastName: 'Thomas',
    email: 'karen.thomas@example.com',
    role: 'admin',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-04-10',
    lastLoginAt: '2026-02-26',
    storageUsed: 6200,
    apiCalls: 18900,
  },
  {
    id: 12,
    username: 'leo_j',
    firstName: 'Leo',
    lastName: 'Jackson',
    email: 'leo.jackson@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'active',
    joinedAt: '2023-02-05',
    lastLoginAt: '2026-02-22',
    storageUsed: 1400,
    apiCalls: 5200,
  },
  {
    id: 13,
    username: 'mia_w',
    firstName: 'Mia',
    lastName: 'White',
    email: 'mia.white@example.com',
    role: 'viewer',
    plan: 'pro',
    status: 'active',
    joinedAt: '2023-04-19',
    lastLoginAt: '2026-02-21',
    storageUsed: 920,
    apiCalls: 3100,
  },
  {
    id: 14,
    username: 'noah_h',
    firstName: 'Noah',
    lastName: 'Harris',
    email: 'noah.harris@example.com',
    role: 'editor',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-07-30',
    lastLoginAt: '2026-02-26',
    storageUsed: 4500,
    apiCalls: 14200,
  },
  {
    id: 15,
    username: 'olivia_m',
    firstName: 'Olivia',
    lastName: 'Martin',
    email: 'olivia.martin@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'active',
    joinedAt: '2023-06-12',
    lastLoginAt: '2026-02-19',
    storageUsed: 280,
    apiCalls: 890,
  },
  {
    id: 16,
    username: 'paul_g',
    firstName: 'Paul',
    lastName: 'Garcia',
    email: 'paul.garcia@example.com',
    role: 'admin',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-01-03',
    lastLoginAt: '2026-02-26',
    storageUsed: 8900,
    apiCalls: 31200,
  },
  {
    id: 17,
    username: 'quinn_m',
    firstName: 'Quinn',
    lastName: 'Martinez',
    email: 'quinn.martinez@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'active',
    joinedAt: '2023-08-25',
    lastLoginAt: '2026-02-18',
    storageUsed: 150,
    apiCalls: 520,
  },
  {
    id: 18,
    username: 'rachel_r',
    firstName: 'Rachel',
    lastName: 'Robinson',
    email: 'rachel.robinson@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'suspended',
    joinedAt: '2022-10-08',
    lastLoginAt: '2025-12-01',
    storageUsed: 1600,
    apiCalls: 4800,
  },
  {
    id: 19,
    username: 'sam_c',
    firstName: 'Sam',
    lastName: 'Clark',
    email: 'sam.clark@example.com',
    role: 'viewer',
    plan: 'pro',
    status: 'active',
    joinedAt: '2023-05-16',
    lastLoginAt: '2026-02-24',
    storageUsed: 750,
    apiCalls: 2600,
  },
  {
    id: 20,
    username: 'tina_r',
    firstName: 'Tina',
    lastName: 'Rodriguez',
    email: 'tina.rodriguez@example.com',
    role: 'editor',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-09-01',
    lastLoginAt: '2026-02-25',
    storageUsed: 3800,
    apiCalls: 11700,
  },
  {
    id: 21,
    username: 'uma_l',
    firstName: 'Uma',
    lastName: 'Lee',
    email: 'uma.lee@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'active',
    joinedAt: '2023-07-20',
    lastLoginAt: '2026-02-17',
    storageUsed: 200,
    apiCalls: 680,
  },
  {
    id: 22,
    username: 'victor_w',
    firstName: 'Victor',
    lastName: 'Walker',
    email: 'victor.walker@example.com',
    role: 'admin',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-03-15',
    lastLoginAt: '2026-02-26',
    storageUsed: 7100,
    apiCalls: 22500,
  },
  {
    id: 23,
    username: 'wendy_h',
    firstName: 'Wendy',
    lastName: 'Hall',
    email: 'wendy.hall@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'active',
    joinedAt: '2022-12-10',
    lastLoginAt: '2026-02-23',
    storageUsed: 2400,
    apiCalls: 7800,
  },
  {
    id: 24,
    username: 'xander_a',
    firstName: 'Xander',
    lastName: 'Allen',
    email: 'xander.allen@example.com',
    role: 'viewer',
    plan: 'free',
    status: 'inactive',
    joinedAt: '2023-09-05',
    lastLoginAt: '2025-10-12',
    storageUsed: 30,
    apiCalls: 90,
  },
  {
    id: 25,
    username: 'yara_y',
    firstName: 'Yara',
    lastName: 'Young',
    email: 'yara.young@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'active',
    joinedAt: '2023-01-28',
    lastLoginAt: '2026-02-22',
    storageUsed: 1900,
    apiCalls: 6100,
  },
  {
    id: 26,
    username: 'zane_k',
    firstName: 'Zane',
    lastName: 'King',
    email: 'zane.king@example.com',
    role: 'admin',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-02-14',
    lastLoginAt: '2026-02-26',
    storageUsed: 9200,
    apiCalls: 28700,
  },
  {
    id: 27,
    username: 'amber_w',
    firstName: 'Amber',
    lastName: 'Wright',
    email: 'amber.wright@example.com',
    role: 'viewer',
    plan: 'pro',
    status: 'inactive',
    joinedAt: '2023-04-02',
    lastLoginAt: '2025-09-18',
    storageUsed: 410,
    apiCalls: 1500,
  },
  {
    id: 28,
    username: 'blake_l',
    firstName: 'Blake',
    lastName: 'Lopez',
    email: 'blake.lopez@example.com',
    role: 'editor',
    plan: 'pro',
    status: 'active',
    joinedAt: '2023-03-08',
    lastLoginAt: '2026-02-21',
    storageUsed: 1100,
    apiCalls: 4200,
  },
  {
    id: 29,
    username: 'chloe_h',
    firstName: 'Chloe',
    lastName: 'Hill',
    email: 'chloe.hill@example.com',
    role: 'admin',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-06-25',
    lastLoginAt: '2026-02-26',
    storageUsed: 6800,
    apiCalls: 20300,
  },
  {
    id: 30,
    username: 'derek_s',
    firstName: 'Derek',
    lastName: 'Scott',
    email: 'derek.scott@example.com',
    role: 'editor',
    plan: 'enterprise',
    status: 'active',
    joinedAt: '2022-11-18',
    lastLoginAt: '2026-02-24',
    storageUsed: 4100,
    apiCalls: 13600,
  },
];

@Injectable({ providedIn: 'root' })
export class UserService {
  getUsers(): User[] {
    return USERS;
  }

  updateUser(id: number, changes: Partial<User>): User[] {
    const index = USERS.findIndex((u) => u.id === id);
    if (index !== -1) {
      USERS[index] = { ...USERS[index], ...changes };
    }
    return [...USERS];
  }
}
